config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'pages#home'

  resources :lands, only: [:index, :show, :destroy] do
    collection { post :import }
    resources :followlands, only: [:create]
  end

  resources :orders
  
  resources :contacts, only: [:create]

  match '/neighborhoods/find_by_city', to: 'neighborhoods#find_by_city', via: :get
  
end

app/models/city.rb
class City < ActiveRecord::Base

	has_many :lands
	has_many :orders
	has_many :neighborhoods
	belongs_to :user
end

app/models/citysearch.rb
class Citysearch < ActiveRecord::Base
	has_many :orders
	has_many :neighborhoods
	has_many :lands
	belongs_to :user
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	after_create :send_welcome_email
	self.inheritance_column = nil

	private

  def send_welcome_email
    ContactMailer.welcome(self).deliver_now
  end
end

app/models/followland.rb
class Followland < ActiveRecord::Base
	after_create :send_cadastre_email
	belongs_to :user
	belongs_to :land

 	private

  	def send_cadastre_email
    	FollowlandMailer.cadastre(self).deliver_now
  	end
end

app/models/land.rb
class Land < ActiveRecord::Base
	
  validates :surface, presence: true
 	validates :address, presence: true
  
  validates :city_id, presence: true
  validates :citysearch, presence: true
  validates :file, presence:true

  belongs_to :city
  belongs_to :neighborhood
  belongs_to :citysearch
  has_many :followlands
  

  	geocoded_by :full_street_address
  	after_validation :geocode, if: :address_changed?

  	def self.import(file)
	    CSV.foreach(file.path, headers: true) do |row|
	      Land.create! row.to_hash
	    end
  	end

  	def full_street_address
    	[address, city.name].compact.join(', ')
  	end


end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base

	belongs_to :city
	belongs_to :citysearch
	has_many :lands
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	belongs_to :city
	belongs_to :citysearch

	has_many:lands, through: :citysearch
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


   has_many :orders
   has_many :lands, through: :orders
   has_many :cities
   has_many :citysearches
   has_many :followlands

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # For modal Inscription
  helper_method :resource_name, :resource, :devise_mapping
  #

  	def after_sign_in_path_for(resource)
  		lands_path
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	

	def create
		@contact = Contact.new(contact_params)
		if @contact.save
			redirect_to root_path, notice: "Merci, nous avons pris en compte votre demande."
		else
			render :new
		end
	end

	private

	def contact_params
		params.require(:contact).permit(:name, :type, :phone, :description, :mail)
	end


end

app/controllers/followlands_controller.rb
class FollowlandsController < ApplicationController
	before_action :set_land

	def create
		@followland = Followland.new(followland_params)
		@followland.land = @land
		@followland.user = current_user
			if @followland.save
				redirect_to land_path(@land), notice: "Votre mail a bien été envoyé au service du cadastre."
			else
				render:show
			end
	end

	private

	def set_land
		@land = Land.find(params[:land_id])
	end

	def followland_params
		params.require(:followland).permit(:comment)
	end
end

app/controllers/lands_controller.rb
class LandsController < ApplicationController
	before_action :set_land, only: [:show, :destroy]
	def index
    	@lands = current_user.lands.paginate(:page => params[:page], :per_page => 10)
    	@lands = @lands.where(citysearch: params[:citysearch]) if params["citysearch"].present?
    	@lands = @lands.where(neighborhood: params[:neighborhood]) if params["neighborhood"].present?
    	@lands = @lands.where("surface >= ?", params[:min_surface]) if params["min_surface"].present?
    	@lands = @lands.where("surface <= ?", params[:max_surface]) if params["max_surface"].present?	

    	respond_to do |format|
      		format.html # index.html.erb
      		format.json { render json: Land.all.to_json } # index.js.erb
      		format.js {render :index}
      	end
	end

	def home
	end

	def show
    @followland = Followland.new
		@hash = Gmaps4rails.build_markers(@land) do |land, marker|
      		marker.lat land.latitude
      		marker.lng land.longitude
		end
	end

	def new
	end

	def create
	end

	def destroy
		@land.destroy
      	redirect_to lands_path
	end

	def import
  		Land.import(params[:file])
  		redirect_to lands_path, notice: "Les parcelles ont été ajoutées !!"
  	end

	private

  	def set_land
    	@land = Land.find(params[:id])
  	end

  	def land_params
    	params.require(:land).permit(:number, :surface, :address, :neighborhood_id, :city_id, :citysearch_id, :latitude, :longitude, :file)
  	end
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController

  #def show
  # @neighborhoods = Category.find(params[:id])
  #end


  def show
   # @listings = Listing.where(neighborhoods_id: params[:id]).order("created_at DESC")
   @citysearch = Citysearch.find(params[:citysearch_id])
   @neighborhoods = Neighborhood.find(params[:id])
  end

  def find_by_city
    citysearch = Citysearch.find(params[:citysearch_id])
    neighborhoods = citysearch.neighborhoods.find_all
    render json: { neighborhoods: neighborhoods }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@contact = Contact.new
  end


end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

	def create
		email = params[:email]
		@subscriber = SubscribeToNewsletter.new
		@subscriber.call(email)
		flash[:notice] = "Successful Registration"
		redirect_to :back
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# For Modal Iscription
	def resource_name
    	:user
  	end

  	def resource
    	@resource ||= User.new
  	end

  	def devise_mapping
    	@devise_mapping ||= Devise.mappings[:user]
  	end

  	#

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/followlands_helper.rb
module FollowlandsHelper
end

app/helpers/lands_helper.rb
module LandsHelper
end

app/helpers/will_paginate_helper.rb
module WillPaginateHelper
  class WillPaginateJSLinkRenderer < WillPaginate::ActionView::LinkRenderer
    def prepare(collection, options, template)
      options[:params] ||= {}
      options[:params]['_'] = nil
      super(collection, options, template)
    end

    protected
    def link(text, target, attributes = {})
      if target.is_a? Fixnum
        attributes[:rel] = rel_value(target)
        target = url(target)
      end

      @template.link_to(target, attributes.merge(remote: true)) do
        text.to_s.html_safe
      end
    end
  end

  def js_will_paginate(collection, options = {})
    will_paginate(collection, options.merge(:renderer => WillPaginateHelper::WillPaginateJSLinkRenderer))
  end
end

app/views/lands/_results.html.erb
<% if @lands.empty? %>
      <h3> Il n'y a pas de terrains correspondant à votre recherche </h3>
    <% else %>
      <div class="row">
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="text-center">Nous avons trouvé <%= @lands.count %> propriété(s) potentiels correspondant à votre recherche</h4>

            </div>
            <div class="panel-body">
              <% @lands.each do |land| %>
                <div class="row">
                  <div class="col-md-2">
                    <%= land.surface %> m2
                    <p> Fichier n°<%= land.file %></p>
                  </div>
                  <div class="col-md-4">
                    <h4 class="mt-0"><%= land.address %></h4>

                  </div>
                  <div class="col-md-4">
                    <p><%= land.neighborhood.name if land.neighborhood.present? %></p>
                  </div>
                  <div class="col-md-2 right">
                    <p><%= link_to "En savoir plus", land_path(land), target: '_blank' %></p>
                  </div>
                </div>
                <div class= "row">
                  <div class="col-md-12">
                    <%= image_tag("http://maps.googleapis.com/maps/api/streetview?key=AIzaSyCwCp3To_EfAyq9Yt0-x9O2KfQMU4dLRw8&size=640x400&location=#{land.full_street_address}&fov=180&&pitch=1&sensor=false", class: "item-show-map")%>
                    <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?key=AIzaSyCwCp3To_EfAyq9Yt0-x9O2KfQMU4dLRw8&zoom=15&size=440x400&sensor=false&maptype=roadmap&markers=color:red|#{land.full_street_address}", class: "item-show-map2" %>
                  </div>
                </div>
                <% if current_user.try(:admin?) %>
                 <%= link_to "Effacer", land_path(land), method: :delete %>
                <% end %>
                <br><hr><br>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <%= js_will_paginate @posts, renderer: BootstrapPagination::Rails , :params => { :my_excluded_param => nil } %>

app/views/lands/home.html.erb
<div class="jumbotron">
  <h2 class="text-center">All you need is business !</h2>

<%= render 'shared/filter' %>
</div>

app/views/lands/index.html.erb
<div class="container">
  <%= render 'shared/filter' %>

  <br>
  <div id="results">
    <%= render 'results'%>
  </div>
</div>

app/views/lands/index.js.erb
$("#results").html("<%= escape_javascript render("results") %>");

app/views/lands/show.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-8">
            <h4>Vue extérieure du <%= @land.full_street_address %></h4>
          </div>
          <div class="col-md-4">
            <%= simple_form_for [@land, @followland] do |f| %>
              <%= f.hidden_field :comment %>
              <%= f.submit 'Relevé de propriété ?', class:"btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="panel-body">

        <div id="map2" class="map_show"></div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>Plan du <%= @land.full_street_address %></h4>
      </div>
      <div class="panel-body">

        <div id="map3" class="map_show"></div>

      </div>
    </div>
  </div>
  
</div>



<% content_for(:after_js) do %>
  <%= javascript_tag do %>
      $(document).on('ready', function() {

        handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map3' }
        }, function(){
          markers = handler.addMarkers(<%= raw @hash.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          handler.getMap().setZoom(15);
        });
      })
    <% end %>
  <% end %>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
      $(document).on('ready', function() {

        pos = new google.maps.LatLng( <%= @land.latitude %>, <%= @land.longitude %> );

      var div = document.getElementById('map2');
      var sv = new google.maps.StreetViewPanorama(div);
      sv.setPosition( pos );
      sv.setVisible( true );

      // find the heading by looking from the google car pos to the venue pos
      var service = new google.maps.StreetViewService();
      service.getPanoramaByLocation( pos, 50, function(result, status) {
          if (status == google.maps.StreetViewStatus.OK)
          {
              carPos = result.location.latLng;
              heading = google.maps.geometry.spherical.computeHeading( carPos, pos );
              sv.setPov( { heading: heading, pitch: 0, zoom: 1 } );
          }
          else {
          console.log('Street View Noet Available');
        }
} );
      })
    <% end %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    
    <%= yield %>


    
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
  
</html>

<!-- ###### LOG IN MODAL #####-->

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header"><h2 class="text-center"><%= image_tag("logo.png", class: "logo-modal text-center") %></h2>
      <h2 class="text-center modal-titre"> Connectez-vous </h2>
      </div>
      <div class="modal-body">
        <%= form_for(:user, :url => session_path(:user)) do |f| %>
          <%= f.label :email, "Email:", class: '' %>
          <%= f.text_field :email, class: "form-control", style: "margin-bottom:25px", placeholder: "johnsmith@franceimmobilier.fr" %>
          <%= f.label :password, "Mot de passe:", class: '' %>
          <%= f.password_field :password, label: "Mot de passe", class: "form-control", style: "margin-bottom:25px" %>
          <%= f.submit 'Se connecter', class: "form-control btn btn-primary",style: "margin-bottom:25px" %>
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me, "Se souvenir se moi" %>
          <br>
          <%= link_to "Mot de passe oublié ?", new_password_path(:user) %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>
<!-- ##### SIGN UP MODAL ###### -->

<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header"><h2 class="text-center">Inscription</h2>
      </div>
      <div class="modal-body">
        <%= form_for :user, url: user_registration_path do |f| %>
          <%= f.label :email, "Adresse email:", :class=>'' %>
          <%= f.text_field :email, :class =>"form-control", :style => "margin-bottom:25px" %>
          <%= f.label :password, "Mot de passe:", :class=>'' %>
          <%= f.password_field :password,:label =>"Mot de passe", :class =>"form-control", :style => "margin-bottom:25px" %>
          <%= f.submit 'Inscription', :class =>"form-control" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>
  

app/views/pages/home.html.erb
	<div id="header-top">
		<div id="photo">
			<div class="container">
				<h1 class="titre text-center">L'arme fatale pour votre <span class="souligne"> prospection immobilière</span></h1>
				<div class="mt-100 text-center">
					<div class="navbar-wagon-item navbar-wagon-button btn">En savoir Plus</div>
				</div>
			</div>
		</div>
	</div>
	<div id="clients">
		<h2 class="text-center fw-100 mb-30">De nombreux clients nous font déjà confiance</h2>
		<div class="container">
			<div class="row">
				<div class="col-md-offset-1 col-md-10 text-center">
					<%= image_tag ("logo_orpi.png") %>
					<%= image_tag ("logo_era.png") %>
					<%= image_tag ("logo_ladresse.png") %>
					<%= image_tag ("logo_squarehabitat.png") %>
					<%= image_tag ("logo_guyhoquet.png") %>
				</div>
			</div>
		</div>
	</div>
	<div id="contact_image">
		<div id="contact">
			<div class="container">
				<div class="row">
					
					<h2 class="white text-center fw-100 m-30">Nous contacter</h2>
				<div class="row">
					<div class="col-md-6">
						<i class="fa fa-map-marker fa-contact">
						</i>
						<span class="text-contact-address white">17 Avenue des Perdrix 94210 La Varenne Saint Hilaire</span>
						<br>
						<i class="fa fa-phone fa-contact">
						</i>
						<span class="text-contact-phone white ">06 98 85 38 74</span>
						<br>
						<i class="fa fa-envelope fa-contact">
						</i>
						<span class="text-contact-mail white ">alcordani@gmail.com</span>
						
					</div>
					<div class="col-md-6">
						<div class="cadre-contact pt-60">
							<%= simple_form_for @contact do |f| %>
								<%= f.input :name, label: 'Votre Nom/ Prénom et nom Agence', placeholder: 'John Smith, Visites en Vues'%>
								<%= f.input :mail, label: 'Votre mail', placeholder: 'jsmith@fviitesenvues.com' %>
								<%= f.input :phone, label: 'Votre téléphone', placeholder: '0698853874' %>
								<%= f.input :type, label: false, collection: [ "Agence Independante", "Franchisée", "Agent Indépendant"], prompt: "Choisissez un type d'agence" %>
								
								
								<%= f.submit 'Envoyer', class:"navbar-wagon-button center mt-27" %>
							<% end %>
						</div>
					</div>
				</div>




					<div class="col-md-6 col-md-offset-3">
						<% if current_user.try(:admin?) %>
							<h2 class="text-center fw-100">Import Lands</h2>
							<%= form_tag import_lands_path, multipart: true do %>
				  				<span class="btn btn-large btn-warning btn-file">
				    				Choose File
				    				<%= file_field_tag :file %>
				  				</span>
				  				<%= submit_tag "Upload Companies", class: "btn btn-primary" %>
							<% end %>

						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/shared/_filter.html.erb
<div class="container">

          <%= form_tag lands_path, method: :get, class: "text-center",remote: true do %>
            <div class="filter">
              <br>
              <div class="row">
                <div class="col-md-12">
                  <div class="col-md-3">
                    <%= label_tag "Choisissez votre ville" %><br />
                    <%= select_tag(:citysearch,options_for_select(current_user.orders.map{ |c| [c.citysearch.name, c.citysearch.id]}, params[:citysearch]), class: "form-control") %>
                  </div>
                  <div class="col-md-3">
                  <%= label_tag "Choisissez votre quartier" %><br />
                    <%= select_tag(:neighborhood, options_for_select([], params[:neighborhood]), class:"form-control") %>
                  </div>

                  <div class="col-md-2">
                    <%= label_tag "Surface minimum" %><br />
                    <%= text_field_tag :min_surface, params[:min_surface], placeholder:"Ex: 250", class: "form-control"%>
                  </div>

                  <div class="col-md-2">
                    <%= label_tag "Surface maximum" %><br />
                    <%= text_field_tag :max_surface, params[:max_surface], placeholder:"Ex: 300", class: "form-control" %>
                  </div>
                  <div class="col-md-2 mt-27">
                  <%= submit_tag "Recherche", name: nil, class: "btn btn-primary mt-30 btn-filter" %>
                  </div>
                </div>
              </div>
              <div class="row">
               
              </div>
            </div>
          <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

Cool

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <h2 class="logo">L'arme fatale</h1>
  <% end %>

  <!-- Right Navigation -->
  <div class="nav navbar-wagon-right hidden-xs hidden-sm">

    
    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to lands_path do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Rechercher" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <li>
            <%= link_to 'Connexion', "#", data: {toggle: "modal", target: "#myModal"} %>
          </li>
          <!-- <li>
            <%= link_to 'Inscription', "#", data: {toggle: "modal", target: "#myModal2"} %>
          </li> -->

    <% end %>

    <!-- Button (call-to-action) -->
    
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>